### ISSUE TITLE
Space reindex fails with random files when silverbullet-ai is installed 

### ISSUE THREAD

**Issue by thyforhtian** [justyns/silverbullet-ai#52]
Silverbullet version: 0.8.4
silverbullet-ai: latest (as on 30 Jul 2024)

SB fails to index some files (seems random) when silverbullet-ai is installed.

```
Execution of mqSubscription for queue indexQueue invoking processIndexQueue with messages [
  { id: "1722336429347-000089", queue: "indexQueue", body: "PLUGS.md" },
  {
    id: "1722336429347-000090",
    queue: "indexQueue",
    body: "SPACE_SCRIPTS.md"
  },
  {
    id: "1722336429347-000091",
    queue: "indexQueue",
    body: "Holidays.md"
  }
] failed: Error: Cannot read properties of undefined (reading 'generateEmbeddings')
    at LR.onMessage (file:///silverbullet.js:75:8471)
    at Worker.worker.onmessage (file:///silverbullet.js:75:7990)
    at Worker.wrappedHandler (ext:deno_web/02_event.js:1401:12)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
    at Worker.dispatchEvent (ext:deno_web/02_event.js:1043:12)
    at Worker.#pollMessages (ext:runtime/11_workers.js:253:12)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

I tried explicitly disabling embeddings in SETTINGS but it did not help, either.

```
ai:
  indexEmbeddings: false
  ...
```

**Comment by zefhemel** [comment]
I also noticed that `indexEmbeddings` just seems to be ignored right now.

**Comment by justyns** [comment]
Both of these issues should be fixed now.  Let me know if you still see the same errors.  `indexEmbeddings` should also be honored now

**Comment by thyforhtian** [comment]
Seems fixed. Thank you for the quick response, much appreciated!
